### ISSUE TITLE
preciso de ajuda

### ISSUE THREAD

**Issue by Phylliphi** [dedynobre/autenticando-acesso-bot-telegram-com-active-directory#1]
ola nao entendo nada de programacao poderia me ajudar?

**Comment by odenisnobre** [comment]
Olá @Phylliphi qual seria a dúvida?

**Comment by Phylliphi** [comment]
poderia me enviar uma msg no telegram ou whatsapp? para esclarecer melhor (94) 984047892

**Comment by odenisnobre** [comment]
A principio descreva aqui a sua dúvida aqui pois pode ser a dúvida de mais alguém.
Caso precise de mais algum detalhe fora do tópico podemos falar reservadamente.

**Comment by Phylliphi** [comment]
Seria todo o passo a passo mesmo, de como criar a integração, para a autenticação de acesso ao bot, se é necessário ter algum servidor para executar este serviço, se tem um video no youtube!

**Comment by odenisnobre** [comment]
Para esta integração precisamos de duas coisas: 
1) servidor do AD(Active Directory)
2) servidor que está instalado e rodando o Node Red.

As etapas de desenvolvimento consiste em ter um usuário no AD que de preferencia seja de serviço que a senha nunca expire.
Feito isso, é seguir pra programação conforme descrito no projeto.

**Comment by Phylliphi** [comment]
Obrigado, pelas informações
